"""Removed unnecessary fields from orders table

Revision ID: 8b0333879f80
Revises: 9b4841d08fa4
Create Date: 2026-06-24 14:12:13.196677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b0333879f80'
down_revision: Union[str, Sequence[str], None] = '9b4841d08fa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'schedule_days')
    op.drop_column('orders', 'packing_size')
    op.drop_column('orders', 'approve_rate')
    op.drop_column('orders', 'shelf_life_months')
    op.drop_column('orders', 'invoice_submission_date')
    op.drop_column('orders', 'active_quantity_spdr')
    op.drop_column('orders', 'file_no')
    op.drop_column('orders', 'supply_percent')
    op.drop_column('orders', 'hsn_code')
    op.drop_column('orders', 'tax_rate')
    op.drop_column('orders', 'drug_value')
    op.drop_column('orders', 'loa_percent')
    op.drop_column('orders', 'outstanding_to_rmscl')
    op.drop_column('orders', 'amount_passed')
    op.drop_column('orders', 'tender_quantity')
    op.drop_column('orders', 'remarks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('remarks', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('tender_quantity', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('amount_passed', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('outstanding_to_rmscl', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('loa_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('drug_value', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('tax_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('hsn_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('supply_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('file_no', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('active_quantity_spdr', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('invoice_submission_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('shelf_life_months', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('approve_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('packing_size', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('schedule_days', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
