"""Removed id from Order table

Revision ID: a15fdb7bd493
Revises: cebab6eebf66
Create Date: 2026-06-23 11:47:53.302355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a15fdb7bd493'
down_revision: Union[str, Sequence[str], None] = 'cebab6eebf66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'tender_ref_no',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_column('orders', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.alter_column('orders', 'tender_ref_no',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
