"""Created singular Orders table for excel sheet

Revision ID: cebab6eebf66
Revises: aef42dd8323f
Create Date: 2026-06-19 15:36:13.614732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cebab6eebf66'
down_revision: Union[str, Sequence[str], None] = 'aef42dd8323f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_ref_no', sa.String(), nullable=True),
    sa.Column('tender_quantity', sa.Integer(), nullable=True),
    sa.Column('loa_percent', sa.Integer(), nullable=True),
    sa.Column('approve_rate', sa.Float(), nullable=True),
    sa.Column('placebo_required', sa.Boolean(), nullable=True),
    sa.Column('product_code', sa.String(), nullable=True),
    sa.Column('product_name', sa.String(), nullable=True),
    sa.Column('hsn_code', sa.String(), nullable=True),
    sa.Column('packing_size', sa.String(), nullable=True),
    sa.Column('shelf_life_months', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('tax_rate', sa.Float(), nullable=True),
    sa.Column('po_no', sa.Integer(), nullable=True),
    sa.Column('po_date', sa.Date(), nullable=True),
    sa.Column('po_quantity', sa.Integer(), nullable=True),
    sa.Column('drug_value', sa.Integer(), nullable=True),
    sa.Column('po_value', sa.Integer(), nullable=True),
    sa.Column('invoice_qty', sa.Integer(), nullable=True),
    sa.Column('invoice_value', sa.Integer(), nullable=True),
    sa.Column('pending_invoice_qty', sa.Integer(), nullable=True),
    sa.Column('pending_invoice_value', sa.Integer(), nullable=True),
    sa.Column('active_quantity_spdr', sa.Integer(), nullable=True),
    sa.Column('schedule_days', sa.Integer(), nullable=True),
    sa.Column('schedule_date', sa.Date(), nullable=True),
    sa.Column('remaining_days', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('invoice_submission_date', sa.Date(), nullable=True),
    sa.Column('payment_sanction_date', sa.Date(), nullable=True),
    sa.Column('amount_passed', sa.Integer(), nullable=True),
    sa.Column('outstanding_to_rmscl', sa.Integer(), nullable=True),
    sa.Column('file_no', sa.Integer(), nullable=True),
    sa.Column('remarks', sa.String(), nullable=True),
    sa.Column('supply_percent', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.drop_table('files')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_tender_items_id'), table_name='tender_items')
    op.drop_table('tender_items')
    op.drop_table('products')
    op.drop_table('invoices')
    op.drop_table('delivery_statuses')
    op.drop_table('purchase_orders')
    op.drop_table('tenders')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_statuses',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('po_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pending_invoice_quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('pending_invoice_value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('remaining_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('active_quantity_spdr', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('supply_percent', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], name=op.f('delivery_statuses_po_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('delivery_statuses_pkey'))
    )
    op.create_table('companies',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('companies_pkey'))
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_table('purchase_orders',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tender_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('drug_value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('schedule_days', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('schedule_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PO_CLOSED', 'BILL_PROCESS', name='po_status'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name=op.f('purchase_orders_company_id_fkey')),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], name=op.f('purchase_orders_tender_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('purchase_orders_pkey'))
    )
    op.create_table('invoices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('po_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('submission_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('sum', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('amount_passed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], name=op.f('invoices_po_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('invoices_pkey'))
    )
    op.create_table('products',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hsn_code', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('packing_size', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('shelf_life_months', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('products_pkey'))
    )
    op.create_table('tender_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tender_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('tender_items_product_id_fkey')),
    sa.ForeignKeyConstraint(['tender_id'], ['tenders.id'], name=op.f('tender_items_tender_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tender_items_pkey'))
    )
    op.create_index(op.f('ix_tender_items_id'), 'tender_items', ['id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('po_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('payment_sanction_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('outstanding_to_rmscl', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('difference_value', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], name=op.f('payments_po_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('payments_pkey'))
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('po_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('remarks', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], name=op.f('files_po_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('files_pkey'))
    )
    op.create_table('tenders',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('LOA_percent', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('approve_rate', sa.REAL(), autoincrement=False, nullable=False),
    sa.Column('placebo_required', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('tenders_pkey'))
    )
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
